### ISSUE TITLE
Add option to convert entire N5 container

### ISSUE THREAD

**Issue by hanslovsky** [saalfeldlab/paintera-conversion-helper#1]
Add command line option that converts entire N5 container into Paintera compatible format. It is probably best to ignore any additional `-d`/`--dataset` options in that case. I suggest to use `-c`/`--convert-entire-container` as options.

As we have no way of knowing the type (raw or label) of the datasets in the input container, I suggest:
 - label:
   - `UINT64`
   - `UINT32`
   - `INT64`
   - `INT32`
   - `LabelMultisetType`
 - raw:
   - everything else

We should add options/tags for users to override settings on a per data set basis, including the type. The format of that is open for debate, could be json  (`-D{"dataset":{}}`) or a `-D<dataset>:key=value[,key=value...]` scheme, e.g.
```
convert -c /n5/container/specification -o /output/n5/specification -Dsome/dataset:type=label,
```
Once we make a decision what parameters we would like to be able to set, we can choose an appropriately complex scheme.

**Comment by nthistle** [comment]
Added the `-c`/`--convert-entire-container` option in a5c2ad46013fb1221c4de3a75f4d7c6e0a1d41c6, split the other part of the issue into #5.

**Comment by hanslovsky** [comment]
Thanks @nthistle
