### ISSUE TITLE
Store absolute root path for n5-filesystem label-to-block-mapping

### ISSUE THREAD

**Issue by constantinpape** [saalfeldlab/paintera-conversion-helper#13]
If given a relative output path, `paintera-conversion-helper` will store this relative path as `root` in the `labelBlockLookup` entry when creating a project with `label-block-mapping` using n5.
This way, paintera will only find the label-bock mapping, and consequently only generate meshes, if it is called from the same folder.
Instead, the path should be turned into an absolute path, s.t. paintera can be called from any directory.

**Comment by axtimwalde** [comment]
Affected me.  This happens when paintera-conversion-helpers are called with relative paths instead of absolute paths.

**Comment by hanslovsky** [comment]
This is probably fixed in #33 but only for the new `PainteraConvert` class and not the `CommandLineConverter`, which has been deprecated anyway.
